// react-project/src/views/good/components/CateSelect.js
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Select } from 'antd'

import { getCates } from '@/store/actions'
const { Option } = Select

export default props => {

  const { hasAll, onChange, value, allowClear } = props

  const dispatch = useDispatch()
  const { cates } = useSelector(state=>state.good)

  useEffect(()=>{
    dispatch(getCates())
  }, [])

  return (
    <Select
      value={value}
      onChange={onChange}
      style={{display:'block'}}
      placeholder='选择商品品类'
      allowClear={allowClear}
    >
      { hasAll && <Option key='-1' value=''>全部</Option> }
      {
        cates.map(ele=>(
          <Option key={ele._id} value={ele.cate}>{ele.cate_zh}</Option>
        ))
      }
    </Select>
  )
}

// vue-element-admin/src/views/good/components/CateSelect.vue
<template>
  <el-select
    placeholder="全部"
    :value='value'
    @change='$emit("input", $event)'
    clearable
  >
    <el-option
      v-for="item in cates"
      :key="item._id"
      :label="item.cate_zh"
      :value="item.cate">
    </el-option>
  </el-select>
</template>

<script>
import { mapState, mapActions } from 'vuex'
export default {
  props: {
    value: { type: String, default: '' }
  },
  computed: {
    ...mapState('good', ['cates'])
  },
  created () {
    this.getCates()  // 派发执行action方法
  },
  methods: {
    ...mapActions('good', ['getCates'])
  }
}
</script>

<style lang="css" scoped>
</style>
