// vue-element-admin/src/views/good/good-form.vue
<template>
  <div class='good-form'>
    <el-form
      :model="good"
      :rules="rules"
      ref="good"
      label-width="100px"
      class="demo-good"
    >

      <el-form-item label="商品名称" prop="name">
        <el-input v-model="good.name" />
      </el-form-item>

      <el-form-item label="商品描述" prop="desc">
        <el-input type="textarea" v-model="good.desc" />
      </el-form-item>

      <el-form-item label="商品品类" prop="cate">
        <cate-select v-model='good.cate' />
      </el-form-item>

      <el-form-item label="商品价格" prop="price">
        <el-input-number
          v-model.number="good.price"
          controls-position="right"
          :min='0'
        />
      </el-form-item>

      <el-form-item label="是否热销" prop="hot">
        <el-switch v-model="good.hot"></el-switch>
      </el-form-item>

      <el-form-item label="商品图片" prop="img">
        <!-- :value='good.img' + @input='good.img=$event' -->
        <img-upload v-model='good.img' />
      </el-form-item>

      <el-form-item>
        <el-button type="primary" @click="submit">
          {{ id ? "修改" : "添加" }}
        </el-button>
      </el-form-item>

    </el-form>
  </div>
</template>

<script>
import CateSelect from './components/CateSelect.vue'
import ImgUpload from './components/ImgUpload.vue'
import validate from './utils/validate'
import { fetchGoodSubmit, fetchGoodInfo } from '@/api/good'
export default {
  props: {
    id: { type: String, default: '' }
  },
  components: {
    CateSelect,
    ImgUpload
  },
  data () {
    return {
      // 用于收集Form中多个表单的值
      good: {
        name: '',
        desc: '',
        price: 0,
        hot: false,
        cate: '',
        img: ''
      },
      rules: validate
    }
  },
  created () {
    // const id = this.$route.params.id
    // console.log('id', id)
    if (this.id) {
      fetchGoodInfo(this.id).then(res=>{
        // console.log('商品详情', res)
        this.good = res.data.info
      })
    }
  },
  methods: {
    submit () {
      let data = { ...this.good }
      // 有id是编辑，没有id是新增
      if (this.id) data['id'] = this.id
      fetchGoodSubmit(data).then(res=>{
        // 上传成功时，弹框提示用户成功
        this.$message({
          message: `${this.id?"修改":"添加"}成功`,
          type: 'success',
          duration: 1000,
          onClose: () => {
            // console.log('this', this)
            // 注意this指向问题
            this.$router.back()
          }
        })
      })
    }
  }
}
</script>

<style lang="scss" scoped>
  .good-form {
    box-sizing: border-box;
    padding: 25px;
    max-width: 600px;
  }
</style>

<style lang='scss'>
  .good-form {
    .el-input-number .el-input__inner {
      text-align: left;
    }
  }
</style>

// react-project/src/views/good/GoodForm.js
import { useSelector, useDispatch } from 'react-redux'
import { useHistory, useParams } from 'react-router-dom'
import { useEffect } from 'react'

import { Form, Input,
  InputNumber,
  Cascader,
  Select,
  Row,
  Col,
  Checkbox,
  Button,
  Switch,
  message,
  AutoComplete } from 'antd'

// 自定义的表单验证方法
import { validatePrice } from '@/utils/validate'
// 三个自定义封装组件（二次封装）
import CateSelect from './components/CateSelect'
import SingleUpload from './components/SingleUpload'
import GoodQuill from './components/GoodQuill'

import { submitGood, resetGood, getGoodInfo } from '@/store/actions'

const { Option } = Select

export default () => {

  const [form] = Form.useForm()  // 得到Form实例
  const dispatch = useDispatch()
  const history = useHistory()
  const { id } = useParams()
  const { done, info } = useSelector(state=>state.good)

  console.log('--info', info)

  const submit = (values) => {
    console.log('提交', values)
    let data = {...values}
    if (id) data['id'] = id
    dispatch(submitGood(data))
  }

  useEffect(()=>{
    if (id) {
      dispatch(getGoodInfo(id))
    }
  }, [])

  useEffect(()=>{
    if (info._id) {
      form.setFieldsValue(info)
    }
  }, [info])

  useEffect(()=>{
    if (done) {
      message.success(`${id?'修改':'添架'}成功`, 1, ()=>{
        history.goBack()
      })
    }
    return () => {
      dispatch(resetGood())
    }
  }, [done])

  return (
    <div className='goodform'>
      <Form
        labelCol={{span: 3}}
        wrapperCol={{span: 12}}
        form={form}
        onFinish={submit}
        initialValues={{
          img: ''
        }}
        scrollToFirstError
      >
        <Form.Item
          name="name"
          label="商品名称"
          validateTrigger={['onBlur','onChange']}
          rules={[
            { required: true, message: '请输入商品名称' },
            { pattern: /^[\u4e00-\u9fa5]{4,6}/, message:'商品名称只能中文，并且4~6个字' }
          ]}
        >
          <Input />
        </Form.Item>

        <Form.Item
          name="desc"
          label="商品描述"
          validateTrigger='onBlur'
          rules={[
            { required: true, message: '请输入商品描述' },
            { min: 10, max: 20, message: '商品描述要求10~20字' }
          ]}
        >
          <Input.TextArea rows={3} />
        </Form.Item>

        <Form.Item
          name="price"
          label="商品价格"
          validateTrigger='onBlur'
          rules={[
            { required: true, message: '请输入价格' },
            // ({ getFieldValue }) => ({
            //   validator: (rule, value) => {
            //     if (value < 1) {
            //       return Promise.reject(new Error('商品价格不能小于1元'))
            //     } else {
            //       return Promise.resolve()
            //     }
            //   }
            // }),
            { validator: validatePrice(10) }
          ]}
        >
          <InputNumber/>
        </Form.Item>

        <Form.Item
          name="cate"
          label="商品品类"
          validateTrigger='onChange'
          wrapperCol={{span:3}}
          rules={[
            { required: true, message: '品类是必填属性', },
          ]}
        >
          <CateSelect />
        </Form.Item>

        <Form.Item
          name="hot"
          label="是否热销"
          valuePropName='checked'
        >
          {/* 被Form.Item包裹的表单，相当于给了value+onChange */}
          <Switch />
        </Form.Item>

        <Form.Item
          name="img"
          label="商品图片"
          rules={[
            { required: true, message: '请上传商品图片' }
          ]}
        >
          <SingleUpload />
        </Form.Item>

        <Form.Item wrapperCol={{span:12,offset:3}}>
          <Button type="primary" htmlType="submit">
            { id ? '修改' : '添加' }
          </Button>
        </Form.Item>
      </Form>

      <GoodQuill />
    </div>
  )
}
